# Site settings
course_name: TechNoon
course_description: null
course_semester: null

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://technoon.org/" # the base hostname & protocol for your site

title: TechNoon
description: Lunchtime technical training by industry for industry

schoolname: null
schoolurl: null
twitter_username: null
github_username: technoon-org

address: null

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%Y-%m-%d"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
